server:
 port: 5000

spring:
 config:
  import: optional:dotenv:.env
 application:
  name: homeproject
  
 sql:
  init:
   mode: always
   
 datasource:
  #나중에 aws에 연동할때 localhost를 RDS의 엔드포인트로 변경 및 아이디 비밀번호 변경.
  #url: jdbc:mysql://localhost:3306/homeproject
  url: jdbc:mysql://homepoject-rds.c1u4y20ygl3s.ap-northeast-2.rds.amazonaws.com:3306/homeproject
  username: admin
  password: 12341234
  driver-class-name: com.mysql.cj.jdbc.Driver
  
 jpa:
  defer-datasource-initialization: true
  open-in-view: false
  show-sql: true
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true

springdoc:
 api-docs:
  path: /v/api-docs
  #OpenAPI 명세가 노출되는 경로 설정
  #기본값은 /v3/api/docs
  #브라우저에서 확인가능하다 : http://localhost:포트/v3/api-docs
 swagger-ui:
  path: /swagger-ui.html
  #SwaggerUI 웹페이지 접속 경로 설정
  #기본값은 /swagger-ui/index.html
  #이 설정을 통해 /swagger-ui.html로 간편하게 접속 가능하다.
  
cloud:
 aws:
  s3:
   bucket : ${AWS_BUCKET}
   path: 
    review: userImg
  region:
   static: ap-northeast-2
  stack:
   auto: false
  credentials:
#EC2로 백엔드를 올릴경우 해당 EC2에서 환경 변수를 다시 설정해줘야함
#그리고 지금 있는 ACCESSKEY는 로컬용이니까 다시 받아야함.
   accessKey: ${AWS_ACCESS_KEY}
   secretKey: ${AWS_SECRET_KEY}
