name: Deploy to EC2 and Upload to S3

on:
 push:
  branches: [master]

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: set up jdk
    uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: 17

  - name: Grant execute permission for gradlew
    run: chmod +x ./Back/homeproject/gradlew

  - name: Build springboot app
    run: |
     cd Back/homeproject
     ./gradlew clean build -x test

  - name: Check build output files
    run: ls -l ./Back/homeproject/build/libs/

  - name: Copy JAR file to EC2
    uses: appleboy/scp-action@v0.1.7
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_KEY }}
      source: "./Back/homeproject/build/libs/project-0.0.1-SNAPSHOT.jar"
      target: "/home/ubuntu/"

  - name: Execute SSH Commands on EC2
    uses: appleboy/ssh-action@v1.0.0
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_KEY }}
      script: |
        echo "Killing existing Spring Boot process if running..."
        screen -S spring-server -X quit || true

        echo "Starting Spring Boot in new screen session..."
        screen -dmS spring-server java -jar /home/ubuntu/project-0.0.1-SNAPSHOT.jar